[server]
port = 8501
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false

[global]
developmentMode = false

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[runner]
magicEnabled = true
installTracer = true
fixMatplotlib = true

[deprecation]
showPyplotGlobalUse = false 